### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by vchrisb** [DrPsychick/docker-cups-airprint#19]
`docker-cups-airprint` does work fine on arm64 💯 

I only disabled IPv6 and limited to eth0 for avahi.
I'm running it on kubernetes with host networking and without limiting to eth0 it would announce way to many interfaces.

```
sed -i 's/^.*allow-interfaces=.*/allow-interfaces=eth0/' /etc/avahi/avahi-daemon.conf
sed -i 's/^.*use-ipv6=.*/use-ipv6=no/' /etc/avahi/avahi-daemon.conf
#sed -i 's/^.*enable\-reflector=.*/enable\-reflector\=yes/' /etc/avahi/avahi-daemon.conf
#sed -i 's/^.*reflect\-ipv=.*/reflect\-ipv\=yes/' /etc/avahi/avahi-daemon.conf
sed -i 's/^.publish-aaaa-on-ipv4=.*/publish-aaaa-on-ipv4=no/' /etc/avahi/avahi-daemon.conf
```

My image can be found here https://hub.docker.com/repository/docker/vchrisb/airprint-bridge/general

**Comment by DrPsychick** [comment]
Awesome!

I would now add a few variables to make this configurable:
```
AVAHI_INTERFACES=${AVAHI_INTERFACES:=""}
AVAHI_IPV6=${AVAHI_IPV6:="no"}
AVAHI_REFLECTOR=${AVAHI_REFLECTOR:="no"}
```

I would set "publish-aaaa-on-ipv4" based on the IPV6 variable, if "no", then this is "no" as well.

Do you agree @vchrisb ?

**Comment by DrPsychick** [comment]
See https://github.com/DrPsychick/docker-cups-airprint/commit/327c11ff0a955c40758ae55f4f25d48f007169c1

It would be awesome if you could test it as I don't have the environment to verify that it's working as intended. `dev` image should be built within the next 30 min. on Docker hub.

**Comment by vchrisb** [comment]
thx @DrPsychick 
do you have a possibility to add multi arch builds to travis? 
`docker buildx` could be a easy way to achieve that.
I use:
```
export IMAGE="airprint-bridge"
export VERSION="snapshot"
docker buildx create --name mybuilder
docker buildx use mybuilder
docker buildx inspect --bootstrap
docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 . -t vchrisb/${IMAGE}:latest --push
```

**Comment by vchrisb** [comment]
the dev branch works great without modification. I only had to create the image for arm64.

**Comment by DrPsychick** [comment]
I was also thinking of adding automated multiarch build, but I have no experience with it yet, so many thanks for your commands. I'll try it, dunno if travis supports that.

**Comment by DrPsychick** [comment]
pushed a dev arm image manually -> closed.

full multi-arch build will be covered here: https://github.com/DrPsychick/docker-cups-airprint/issues/21
