### ISSUE TITLE
persistent configuration via volume creation

### ISSUE THREAD

**Issue by arko36** [DrPsychick/docker-cups-airprint#26]
Hi,
I think it would be easier to make the printers.conf and other custom config persistent using a specific volume
I did
docker volume create cups
then I added a (-v /cups:/etc/cups) in the docker run command
I have already saved the printers.conf in the hst as you mentioned so I have just copy it
cp printers.conf /var/lib/docker/volumes/cups/_data/
restarted the container and the printers remains

Thanks

**Comment by DrPsychick** [comment]
Sure, feel free!
The idea of the image is that you don't **need** to mount a volume, but you always can.

So I'll close this as "won't fix"
