### ISSUE TITLE
Idle - "File "/usr/lib/cups/filter/brlpdwrapperdcpj315w" not available: No such file or directory" error

### ISSUE THREAD

**Issue by wojciehm** [DrPsychick/docker-cups-airprint#28]
Hello.

I think your idea is super cool to provide automated way to share drivers with AirPrint. I have running well Brother DPC-J315W connected to several end users (Windows 10, Linux). I finally want to enable my users to use iOS AirPrint.

I installed your Docker Image and I try configure my printer with following steps. 
![image](https://user-images.githubusercontent.com/19718255/104731500-12343e00-573c-11eb-9d06-8fc313750071.png)

then

![image](https://user-images.githubusercontent.com/19718255/104731581-35f78400-573c-11eb-9568-f8c18d32ef5f.png)

I add PPD file - source from Brother drivers. https://pastebin.com/Ryc7sc7y

![image](https://user-images.githubusercontent.com/19718255/104731618-43147300-573c-11eb-9bcc-3131888077b6.png)

I have an error ```Idle - "File "/usr/lib/cups/filter/brlpdwrapperdcpj315w" not available: No such file or directory"```

![image](https://user-images.githubusercontent.com/19718255/104732007-d3eb4e80-573c-11eb-8406-5f64f4313daf.png)
How can I fix it?

**Comment by DrPsychick** [comment]
Hey @wojciehm,

that is indeed a great use case! Let me try to help.

Yes you can configure your printer over the interface, but the configuration won't last and same goes for the uploaded `PPD`. It's gone once the container restarts. So after you configure your printer, you need to get the configuration and add it through ENV (see https://github.com/DrPsychick/docker-cups-airprint#add-printer-through-env) or other means to the container when you start it the next time. (Hint: `lpadmin -i ppd-file   #  Specify a PPD file for the printer)`

To get your `PPD` file into the container, I suggest mounting a directory which contains your `PPD` files.

something like:
```
docker run -d --rm -e CUPS_WEBINTERFACE="yes" \
  -v /my/ppd/directory:/etc/cups/ppd \
  -e CUPS_REMOTE_ADMIN="yes" --hostname mycups \
  -e CUPS_LPADMIN_PRINTER1="lpadmin -p "My PPD Printer" ... -i /etc/cups/ppd/myppdfile.ppd ..."
  --name cups-setup drpsychick/airprint-bridge
```

The alternative approach is building your own docker image and including your PPD in it directly, as described here: https://github.com/DrPsychick/docker-cups-airprint#automated-through-files

I hope this helps!

**Comment by DrPsychick** [comment]
Hey @wojciehm, did you get it to work with your custom PPD file?

**Comment by DrPsychick** [comment]
Hey @wojciehm, I'll close this as there is no change required. I hope you got it to work.
