### ISSUE TITLE
"AirPrint" Prefix: Customization Options (enable/disable/change)

### ISSUE THREAD

**Issue by NeoMod** [DrPsychick/docker-cups-airprint#34]
I was wondering if it's possible to customize the "AirPrint" prefix for shared printers.

If possible at all, It would be useful to determine a custom prefix or to be able to enable/disable the prefix at all.

Thanks in advance for any hint on the matter.

**Comment by DrPsychick** [comment]
`/opt/airprint/printer-update.sh` calls `/opt/airprint/airprint-generate.py` without additional options.

it accepts the option `--prefix` which defaults to "AirPrint-"
```
  -p PREFIX, --prefix=PREFIX
                        Prefix all files with this string
```

So, in a PR, one could add an environment variable and pass that through to this script.

**Comment by NeoMod** [comment]
Thanks a lot!
