### ISSUE TITLE
Container is crashing(realtime clock)

### ISSUE THREAD

**Issue by moritzxbe** [DrPsychick/docker-cups-airprint#37]
Hello, my container is crashing.

I have done created an docker compose file:
`version: '2'
services:
  cups:
    image: drpsychick/airprint-bridge:latest
    container_name: cups
    network_mode: host
    restart: unless-stopped
    volumes:
      - /home/pi/cups/config:/config
      - /home/pi/cups/services:/services
    environment:
      - CUPS_ADMIN_USER=admin
      - CUPS_ADMIN_PASSWORD=airprint_2846
      - CUPS_WEBINTERFACE=yes
      - CUPS_REMOTE_ADMIN=yes`

and when I execute docker-compose up on an raspberry pi I get the following error:
sleep: cannot read realtime clock: Operation not permitted

Does anyone know what I am doing wrong?

**Comment by DrPsychick** [comment]
xhttps://unix.stackexchange.com/questions/598471/docker-container-shows-sleep-cannot-read-realtime-clock-operation-not-permit

seems you need to run `--privileged` in this case
