### ISSUE TITLE
Airprint print PDF

### ISSUE THREAD

**Issue by master-ang** [DrPsychick/docker-cups-airprint#38]
airprint ，
ios devices can only print images, but cannot print pdf, word, web pages, etc.
My printer is a black and white printer, I guess it’s a cups-filter problem

**Comment by DrPsychick** [comment]
I'm honestly not sure if I can be of help. You can check the logs of the docker container and see if there are some errors. You can also try printing from other devices (windows/macOS) to see if they have the same issue. If so, you may want to try a different printer driver.

**Comment by master-ang** [comment]
Thank you for your reply. I have no problems printing on windows and macos. Your program is very good. Only ios has trouble printing PDF. At present, I can use another AirPrint program, but the cups version of that program is relatively low. Still want to use your program. Please tell me how to view the log, my view log is blank.

**Comment by master-ang** [comment]
And I tested all the drivers, it’s not a driver problem.

**Comment by DrPsychick** [comment]
you should be able to follow the logs with `docker logs -f <name-of-your-container>` and then try to print.

**Comment by master-ang** [comment]
W [17/Dec/2021:20:04:04 +0800] [Job 1] Grayscale/monochrome printing requested for this job but Poppler is not able to convert to grayscale/monochrome PostScript.
W [17/Dec/2021:20:04:04 +0800] [Job 1] Use \"pdftops-renderer\" option (see cups-filters README file) to use Ghostscript or MuPDF for the PDF -> PostScript conversion.

**Comment by master-ang** [comment]
After this, all the signal lights of my printer are all on, and it must be restarted to return to normal.

**Comment by DrPsychick** [comment]
Looks like you have to manually adjust/add cups-filters. I haven't done that before to be honest, so I can't help you with that.

After searching around a bit, I found this: https://eloquence.marxmeier.com/sdb/html/1123683643.html But I'm not sure if that will lead to a solution.

Alternatively, looking into the "popper" topic, this might give a hint: https://github.com/OpenPrinting/cups-filters/issues/169#issuecomment-549576531

**Comment by master-ang** [comment]
Thank you for your help! I read the content in the link, and to be honest, it is very difficult for me to modify your docker. I use QNAP NAS, and use your docker directly through the GUI. I tried to adjust it using the terminal, but encountered many errors. I'm just curious why another docker named “firilith” can print PDF files, but yours can't. firilith's docker doesn't seem to have a filter either, but it takes a long time to print PDF files.

**Comment by master-ang** [comment]
The same pdf file, printed with ios and printed with pc, have different transmission sizes.


HP_LaserJet_1320_series-6 | Unknown | Withheld | 183k | Unknown | canceled atSat Dec 25 02:14:00 2021 |  
-- | -- | -- | -- | -- | -- | --
HP_LaserJet_1320_series-7 | Unknown | Withheld | 3932k | 1 | completed atSat Dec 25 02:17:05 2021

**Comment by master-ang** [comment]
A miracle happened, I accidentally changed another driver today, and the problem was solved.This issue can be closed.

**Comment by DrPsychick** [comment]
Can you elaborate for the after world which driver you changed? Or was it unrelated to the cups?

**Comment by master-ang** [comment]
My printer is hp laserjet 1320. I have tested its drivers one by one, and they all have the same problem. The driver I often use recently is HP LaserJet 1320 series Postscript (recommended) (en). Yesterday, I found out that your software was updated, so I updated it and chose another driver (HP LaserJet 1320 Series hpijs pcl3, 3.20.3), so it worked.

**Comment by DrPsychick** [comment]
Thank you for sharing your problem and solution. Closing this now as it is solved.
