### ISSUE TITLE
update avahi service file for Location field

### ISSUE THREAD

**Issue by vajonam** [DrPsychick/docker-cups-airprint#41]
couple of updates.

I think will be nice to drop the "Airpint %s @ host" to just %s

```
                name = tree.find('name')
                name.text = '%s' % (v['printer-info'])
```

This uses the printer-info which is a human friendly descriptions which is specified in the `-d` for cups. Maybe we can make this configureable if you want to use `name.text = '%s' % (v['printer-info'])` or `name.text = 'Airprint %s' @ %%h' % (v['printer-info'])`

As well as use the correct location field for the note  which is shown as location on most devices.

```
                desc = Element('txt-record')
                desc.text = 'note=%s' % (v['printer-location'])
```

**Comment by vajonam** [comment]
![image](https://user-images.githubusercontent.com/152501/180790571-c065cf6f-3585-4809-99be-0b3c3ed59fb0.jpeg)

**Comment by DrPsychick** [comment]
Yes, that sounds like a useful enhancement/addition. Are you willing to open a PR for that?

**Comment by vajonam** [comment]
Created PR #43

**Comment by vajonam** [comment]
Thanks this is in after #44  and #43
