### ISSUE TITLE
Update Ubuntu Version.

### ISSUE THREAD

**Issue by TheGreatestJannet** [DrPsychick/docker-cups-airprint#48]
Looking at the DockerFile it seems it uses Eoan otherwise known as Ubuntu 19.10. This version has been end of life since July 2020.
Could the Ubuntu version be updated to a version that is supported.

**Comment by DrPsychick** [comment]
That's an unfortunate default, I agree. But the master builds and pushes multiple versions, see the tags on docker hub: https://hub.docker.com/r/drpsychick/airprint-bridge/tags

**Comment by TheGreatestJannet** [comment]
what does the latest tag use?

**Comment by DrPsychick** [comment]
`FROM ubuntu:$UBUNTU_VERSION`, so it takes `latest` from ubuntu
