### ISSUE TITLE
How can I add a printer shared through an Airport Express?

### ISSUE THREAD

**Issue by ooii** [DrPsychick/docker-cups-airprint#50]
Hi,

I try to make my Brother printer available via AirPrint. It's plugged via USB to an Airport Express which makes it appear on my network.
On my Macbook cups web ui, I can see the following information about it:
```
Description: | Brother HL-1110 series
Location: AirPort
Driver: Brother HL-1110 series CUPS (grayscale)
Connection: dnssd://Brother%20HL-1110%20series._riousbprint._tcp.local./Brother%20HL-1110%20series%20H3N343080
Defaults: job-sheets=none, none media=na_letter_8.5x11in sides=one-sided
```
But I can't figure out how I can add it to my cups AirPrint server. I already tried using the IP address of the Airport Express with `lpadmin -p myprinter -E -v "ipp://192.168.1.146/ipp/print"` (not sure how I can customize the `/ipp/print` at the end) and also using the `dnssd` uri from the previous description without success.
If you have any idea about that, I'll be happy to test it. 
Thank you very much.

**Comment by DrPsychick** [comment]
I have never done that nor do I have a setup to test with, so I cannot really help.
Maybe this gives you some hints? https://www.isi.edu/~calvin/airprint.htm

**Comment by ooii** [comment]
Thanks a lot. I managed to make it working. Information on the provided link was very useful.
