### ISSUE TITLE
Regarding #45 - color-supported not avaible breaks airprint-generate.py

### ISSUE THREAD

**Issue by burnbabyburn** [DrPsychick/docker-cups-airprint#59]
@vajonam 

Hi, i am coming from this [commit](https://github.com/DrPsychick/docker-cups-airprint/commit/d4c701b5a2897897413b22bd705c74159a579acc)
In the past i had removed the gpc stuff on a local checkout myself. And your very nice container worked fine for months
ATM i am migrating my docker host and tried to go with upstream again
But it seems pull #45 killed it for me 

output:
```
cups-airprint  | The dockerized CUPS instance is now ready for use! The web
cups-airprint  | interface is available here:
cups-airprint  | URL:       http://192.168.1.253:631/ or http://futros740:631/
cups-airprint  | Username:  admin
cups-airprint  | Password:  admin
cups-airprint  |
cups-airprint  | ===========================================================
cups-airprint  | Traceback (most recent call last):
cups-airprint  |   File "/opt/airprint/airprint-generate.py", line 299, in <module>
cups-airprint  |     apg.generate()
cups-airprint  |   File "/opt/airprint/airprint-generate.py", line 179, in generate
cups-airprint  |     if attrs['color-supported']:
cups-airprint  | KeyError: 'color-supported'
```

printer creation:
```
- CUPS_LPADMIN_PRINTER1=lpadmin -D "HP laserJet M2727 MFP" -p LaserJet123 -v lpd://10.0.0.29/queue -L LivingRoom -o HPOption_Duplexer=true -o Resolution=1200dpi -o PageSize=A4 -o Duplex=DuplexNoTumble -o MediaType=Plain -o Smoothing=off -o HPEconoMode=false -o HPServicesWeb=ProductManuals -o printer-error-policy=abort-job -o cupsIPPSupplies=true
- CUPS_LPADMIN_PRINTER1_ENABLE=cupsenable LaserJet123
- CUPS_LPADMIN_PRINTER1_ACCEPT=cupsaccept LaserJet123
```

the attrs array parsed in python script (this is from manual adding via cups interface and trying hplip address for more information so ignore device uri)
[arry parsed in pythonscript.txt](https://github.com/DrPsychick/docker-cups-airprint/files/10388664/arry.parsed.in.pythonscript.txt)

Adding the `color-supported` to `CUPS_LPADMIN_PRINTER1` was not sufficient 

(Only) after removing the `color-supported` option from `airprint-generate.py` creating an avahi service was successful
Commenting out wasn't ideal, so i did some research. Seems to me like the value checked for color isn't ideal and/or needs a fallback:

- ["print-color-mode-default/print-color-mode-supported": A list of supported color printing modes, for example 'bi-level', 'monochrome', and 'color'.](https://www.pwg.org/ipp/ippguide.html)
- [color-supported is valid and included in RFC, but it seems like it's not existent on every printer](https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml)
- [Bonjour Print Specification e.g. for the last options missing here like the finishing options or duplex](https://developer.apple.com/bonjour/printing-specification/bonjourprinting-1.2.1.pdf)
- [OMV AVAHI service script in python 2  (?) with duplex detection](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-cups/blob/master/usr/sbin/omv-cups-avahi)

Sadly my python skills s**** and my printer is not supporting that much, so i leave the additional information here and maybe get back to it

the quick fix for me is to just comment out the commit mentioned above

Greetings

**Comment by DrPsychick** [comment]
It might be that a simple change could fix it:
`if attrs['color-supported']:` -> `if 'color-supported' in attrs:`

Let me know if that helps @burnbabyburn , then I can update the code quickly.

**Comment by burnbabyburn** [comment]
@DrPsychick 
Thx for the fix. Worked for me

**Comment by vajonam** [comment]
sorry the late response. I have moved to a printer that supports air print natively so haven't been using this container much recently.

**Comment by DrPsychick** [comment]
should be fine now, thanks for the extremely fast feedback @burnbabyburn !
